# Exclude a variety of commonly ignored directories.
exclude = [
    "*.egg-info",
    "*.pyc",
    ".bzr",
    ".cache",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pycache__",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "docs",
    "node_modules",
    "shared-venv",
    "site-packages",
    "venv",
]

line-length = 100
indent-width = 4
target-version = "py37"

[lint]
select = [
    "B",
    "C",
    "E",
    "F",
    "N",
    "W",
    "B9",
]
ignore = [
    "B905",
    "C901",
    "E203",
    "E501",
    "E722",
    "N802",
    "N803",
    "N804",
    "N806",
    "N815",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
